# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=200)),
                ('data_type', models.CharField(max_length=200)),
                ('mandatory', models.BooleanField(default=False)),
            ],
        ),
    ]
