# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=200)),
                ('data_type', models.CharField(max_length=200)),
                ('data_format', models.CharField(blank=True, max_length=200)),
                ('mandatory', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=200)),
                ('help_text', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalField',
        ),
    ]
