# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_auto_20170202_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='mandatory',
            new_name='required',
        ),
    ]
