# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0003_auto_20170202_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='category',
            new_name='key_category',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='help_text',
            new_name='key_help',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='data_format',
            new_name='value_format',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='required',
            new_name='value_required',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='data_type',
            new_name='value_type',
        ),
    ]
