# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0004_auto_20170202_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='value_required',
            new_name='key_required',
        ),
    ]
